import 'package:equatable/equatable.dart';

class Transaction extends Equatable {
  final String id;
  final String propertyId;
  final String type;
  final String category;
  final double amount;
  final String? paidBy;
  final DateTime transactionDate;
  final String? description;
  final bool hasDocument;
  final String? documentUrl;
  final String? documentName;
  final bool verified;
  final String? reconciliationStatus;
  final bool isAutoGenerated;
  final String createdBy;
  final DateTime createdAt;

  const Transaction({
    required this.id,
    required this.propertyId,
    required this.type,
    required this.category,
    required this.amount,
    this.paidBy,
    required this.transactionDate,
    this.description,
    this.hasDocument = false,
    this.documentUrl,
    this.documentName,
    this.verified = false,
    this.reconciliationStatus,
    this.isAutoGenerated = false,
    required this.createdBy,
    required this.createdAt,
  });

  factory Transaction.fromJson(Map<String, dynamic> json) {
    return Transaction(
      id: json['id'] as String,
      propertyId: json['property_id'] as String,
      type: json['type'] as String,
      category: json['category'] as String,
      amount: (json['amount'] as num).toDouble(),
      paidBy: json['paid_by'] as String?,
      transactionDate: DateTime.parse(json['transaction_date'] as String),
      description: json['description'] as String?,
      hasDocument: json['has_document'] as bool? ?? false,
      documentUrl: json['document_url'] as String?,
      documentName: json['document_name'] as String?,
      verified: json['verified'] as bool? ?? false,
      reconciliationStatus: json['reconciliation_status'] as String?,
      isAutoGenerated: json['is_auto_generated'] as bool? ?? false,
      createdBy: json['created_by'] as String,
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }

  Map<String, dynamic> toJson() => {
    'id': id,
    'property_id': propertyId,
    'type': type,
    'category': category,
    'amount': amount,
    'paid_by': paidBy,
    'transaction_date': transactionDate.toIso8601String().split('T')[0],
    'description': description,
    'has_document': hasDocument,
    'document_url': documentUrl,
    'document_name': documentName,
    'verified': verified,
    'reconciliation_status': reconciliationStatus,
    'is_auto_generated': isAutoGenerated,
    'created_by': createdBy,
    'created_at': createdAt.toIso8601String(),
  };

  @override
  List<Object?> get props => [id, propertyId, type, category, amount, transactionDate];
}
